spring:
  application:
    name: ECOMMERCAPPLICATION
  # Database connection settings
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db?serverTimezone=UTC
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  #JPA Settings
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true