spring:
  application:
    name: DEMO
  # Database connection settings
  datasource:
    # url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?serverTimezone=UTC
    url: jdbc:postgresql://localhost:5432/projeto?serverTimezone=UTC
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  #JPA Settings
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem